version: "3.9"

services:
  service-client:
    image: service-client:v2
    container_name: service-client
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

  service-vehicules:
    image: service-vehicules:v2
    container_name: service-vehicules
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

  service-reservation:
    image: service-reservation:v2
    container_name: service-reservation
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

networks:
  location-net:
    driver: bridge
