version: "3.9"

services:
  service-client:
    build: ./service-client
    container_name: service-client
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

  service-vehicules:
    build: ./service-vehicules
    container_name: service-vehicules
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

  service-reservation:
    build: ./service-reservation
    container_name: service-reservation
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - location-net

networks:
  location-net:
    driver: bridge
